### PR TITLE
refactor: replace `include` with `#include`

### LINKED ISSUE #3: replace `include` with `#include`
We are considering removing `include` from PLCC (https://github.com/ourPLCC/plcc/issues/99).

Before we do, we need to make sure it's reasonable to replace most occurrences of `include` with `#include`. There are pathological cases where they are not equivalent, but it may be the case for 99% of use-cases it's fine. To this end, we want to try to replace all uses of `include` with `#include` in the `languages` project <https://github.com/ourPLCC/languages>.

I ran `ag '^include'` to find all the uses of `include` in the languages project. Here is a text file with the results: [includes.txt](https://github.com/ourPLCC/languages/files/14324648/includes.txt). Good news, with the exception of some unrelated license files, `include` is only found in `grammar` files. That means we probably don't have any pathological cases.

### PR DESCRIPTION
**Pull request by StoneyJackson**
```
refactor: replace include with #include

---

Closes #3

---

Co-authored-by: Akshar Patel <aksharcommit@gmail.com>
Co-authored-by: Stoney Jackson <dr.stoney@gmail.com>
```

### CODE REVIEW

**Comment by StoneyJackson** [comment]
@jashelio @fosler 

I'm seeing a difference, but it's only in the order of cases in a switch statement in the abstract classes' parse method. I suspect this has to do with Python dict. But this is surprising because as of Python 3.7, dict is supposed to preserve insertion order. So, now I'm not sure.

By manual inspection of the differences, I don't think there will be any functional difference.

In this PR, I add a few scripts to help with the transformation:

* bin/transform.bash LANGUAGE
* bin/keep.bash LANGUAGE
* bin/toss.bash LANGUAGE

These should be deleted before we merge.

Running transform.bash uses sed to replace include with #include in grammar. I generates Java for both the original and new grammar. And it reports a git-style diff. If you like the change, you run keep.bash and when you are ready, commit and push the change. If you don't like it, run toss.bash.

So, I think I'll try a few more before I quit tonight.

**Comment by AksharP5** [comment]
Tested all languages with a grammar that had include statements, and the only differences seemed to be the order of the cases, which should not mess with any functionality.

**Comment by StoneyJackson** [comment]
@jashelio @fosler 

In a separate PR, @AksharP5 created a set of automated tests for all the languages as they are right now (before replacing `include` with `#include`). All the languages have working tests except two: INFIX and LONN. These don't because they're behavior was strange; so he marked their tests to be "skipped".

In this PR, @AksharP5 has replaced all `include` with `#include` in all the languages. He has manually checked that the code each language generates is equivalent to the code it generated before the change. He has also ran the new automated tests and confirmed that they all behave as they did before. Of course, tests are not proofs, but I think we have sufficient confidence to merge this.

The question is, should we merge this now? Course materials have not been updated yet. We could wait, and update course in a related feature branch; and then merge both it and this at the "same time". On the other hand, there is always a risk that a delay in that other effort causes this one to become stale and ultimately fail.

My current feeling is that we should merge this now. The changes are minor from the perspective of a reader (i.e., student). So even if we don't get the course materials changed before a class uses it, the mental adjustment is minimal.

Thoughts?

**Comment by fosler** [comment]
I agree that #include should be merged now.

Can you elaborate on what tests didn't work for INFIX and LONN?

The semantics for INFIX in the Code directory is just a stub. Its only real
purpose is to show how INFIX parsing works and as a starting point for
students to complete the semantics portion of Assignment AC. I can give you
a version of INFIX that has fully defined semantics, but it's not in the
default distribution.

Similarly, the semantics for LONN in the Code directory is just a stub. Its
only real purpose is to show how LONN parsing works and as a starting point
for students to complete the semantics portion of Assignment A2. I can give
you a version of LONN that has fully defined semantics, but it's not in the
default distribution.

Tim

**Comment by jashelio** [comment]
I need to know more about course materials vis-a-vis tests. What is the dependency? We can discuss in person.

**Comment by StoneyJackson** [comment]
@fosler It's fine if INFIX and LONN are stubs. We'll make a note of that in our tests. That way no one things that they should "work" as-is.

@jashelio The relationship between course materials and tests... A quick grep through JNotes shows a few references to `include` that can safely be replaced with `#include`. @AksharP5 is assessing the level of dependence for other materials in <https://github.com/ourPLCC/course> .

**Pull request merged**
