### PR TITLE
Add automated testing in GitPod

### LINKED ISSUE #7: Testing
We need automated regression testing.

## Plan

1. [ ] GitPod: able to run tests from GitPod.

    ```bash
    bin/test.bash
    ```

    Installs missing test dependencies (PLCC, bats, etc.), and runs tests for every language.
    Tests for each language should be under LANG/test for each LANG.
    This will also make it "easy" for ourPLCC/plcc to run all the tests.

2. [ ] CI (Actions): able to run tests in GitHub's Actions.

### PR DESCRIPTION
**Pull request by AksharP5**
```
test: adds initial tests

Tests are implemented using bats.
Run them bin/test.bash.

---

* Closes #7 

---

Authors:

Co-authored-by: Akshar Patel <aksharcommit@gmail.com>
Co-authored-by: Stoney Jackson <dr.stoney@gmail.com>
```

### CODE REVIEW

**Comment by StoneyJackson** [comment]
@AksharP5 

I changed my mind... the `bin/test.bash` should not try to install bats.

However, `.gitpod.yml` should install bats. See

* [GitPod Tasks](https://www.gitpod.io/docs/configure/workspaces/tasks)
    * Look at the one in ourPLCC/plcc
* [Installing Bats](https://bats-core.readthedocs.io/en/stable/installation.html)
    * The GitPod image is based on Ubuntu.

So here is how I would proceed. If you see a better way, go for it.

1. Setup `.gitpod.yml` to install the bats command.
2. Make a single bats test for a language. Choose the easiest one. Run it using bats from the command line.
3. Make bin/test.bash call that test.
4. Add another test.
5. Link it into bin/test.bash
6. And so on.

Let me know if you get stuck or need help.

**Comment by AksharP5** [comment]
@StoneyJackson do we also want PLCC, Python, and Java to be installed in the .gitpod.yml similar to the one in ourPLCC/plcc, or keep that in test.bash? Also added tests for multiple languages, please let me know if there is a better way to do them, or if something is missing.

**Comment by StoneyJackson** [comment]
@AksharP5 Yes, those are needed too. Otherwise the tests can't run.

**Comment by AksharP5** [comment]
### Languages that still need tests:
- [x] LAMBDAQ
- [x] LIST
- [x] LON
- [x] LON2
- [x] LONN
- [x] RANDSCONT
- [x] REFCONT
- [x] THREADCONT

### Language tests not functioning properly?:
- INFIX: Outputting 0 for almost everything, or throwing error during parse.
- ABC: classes not generating properly? No rep class when trying to rep.

### TODO
- [x] use teardown in tests
- [x] change tests in bin
- [x] Skip tests for infix and fix abc
- [x] Complete all tests

**Comment by AksharP5** [comment]
@StoneyJackson 
All tests completed, notes:

### Skipped Tests:
- INFIX 
- LONN - minimum number is always 0, java classes are not implemented fully

### Other:
- LON's test is a parse test, since there seems to be no rep functionality
- CHAR is a scan test, since there are no parse or rep classes

Other than this, everything seems to be working, seems good to merge whenever, unless you see something that needs to be fixed or added?

**Comment by AksharP5** [comment]
@StoneyJackson another thing, I added some more commits to this branch, but it is not updating in here, however if I check the branch in the code section, it is updated, not sure if this is an issue, however just wanted to bring it to your attention. Please let me know if there is something that I can do to fix it.

**Comment by StoneyJackson** [comment]
This is ready to go.

@AksharP5, we should squash the commits on this branch. If you do this, git will list you as the author. Otherwise I'll list you in the commit message using the Co-authored-by syntax.

**Review by StoneyJackson — APPROVED** [review]

**Pull request merged**
